---
#  Kernel MikroTik project
- name: Display resource statistics (routeros)
  community.network.routeros_command:
    commands: /system resource print
  register: routeros_resources

- name: Print res
  debug: var=routeros_resources.stdout_lines

- name: Firewall rules 
  community.network.routeros_command:
    commands: /ip firewall filter add chain=input protocol=icmp action=accept comment="Allow ICMP" 

- name: system command
  routeros_command:
    commands: /system routerboard print
  register: system_print
  
- name: Print firewall
  debug: var=ip_firewall_rules.stdout_lines

- name: Print system
  debug: var=system_print.stdout_lines
